server:
   port: 8070

#spring:
#  autoconfigure:
#    exclude:
#      - org.springframework.boot.autoconfigure.jms.JmsAutoConfiguration
#      - org.springframework.boot.autoconfigure.jms.activemq.ActiveMQAutoConfiguration


#To inject into AppProperties
foo: bar

#Can manage camel context from props
#camel:
#  springboot:
#    jmxEnabled: true
#    allow-use-original-message: true

activemq:
   url: tcp://localhost:61616
   username: admin
   password: admin


routes:
  log: log:ru.otr.integration.smev3client?level=DEBUG&showAll=true&multiline=true