/*
INSERT INTO REQUESTRESPONSE(ASYRID, DOCID, DATE) VALUES ('11', '111', CURRENT_DATE())
INSERT INTO REQUESTRESPONSE(ASYRID, DOCID, DATE) VALUES ('22', '222', CURRENT_DATE())
INSERT INTO REQUESTRESPONSE(ASYRID, DOCID, DATE) VALUES ('33', '333', CURRENT_DATE())
*/


INSERT INTO PERSON VALUES ('Mavr', 'Manson', 22, 'Dubay');
INSERT INTO PERSON VALUES ('Mike', 'Tartanov', 28, 'Moscow');
INSERT INTO PERSON VALUES ('Ivan', 'Petrov', 22, 'Turkey');
