server:
   port: 8070

#spring:
#  autoconfigure:
#    exclude:
#      - org.springframework.boot.autoconfigure.jms.JmsAutoConfiguration
#      - org.springframework.boot.autoconfigure.jms.activemq.ActiveMQAutoConfiguration

camel:
  springboot:
    jmxEnabled: true
    allow-use-original-message: true
    stream-caching-enabled: true

activemq:
   url: tcp://localhost:61616
   username: admin
   password: admin


routes:
  log: log:ru.otr.integration.ais_tarif.asur&showAll=true&multiline=true